# Generated by Django 3.2.15 on 2022-09-16 08:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='first_name',
            new_name='child_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='request',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='last_name',
            new_name='parent_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('0', '15:30 - 15:45'), ('1', '15:45 - 16:00'), ('2', '16:00 - 16:15'), ('3', '16:15 - 16:30'), ('4', '16:30 - 16:45'), ('5', '16:45 - 17:00')], default='0', max_length=80),
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.classname'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.teacher'),
        ),
    ]
